### ISSUE TITLE
Firebase Database structure

### ISSUE THREAD

**Issue by hassanrehman01398** [ykhade/quizapp#2]
Can you please send firebase database structure.I am having problems with it

**Comment by ykhade** [comment]
![topic-datamodel](https://user-images.githubusercontent.com/38380049/86095595-00709f00-ba67-11ea-9ccc-5665dc803d4c.png)
![quiz-datamodel](https://user-images.githubusercontent.com/38380049/86095614-08304380-ba67-11ea-9873-199473de590d.png)
Look at the db.dart file for how to pull from firebase

**Comment by hassanrehman01398** [comment]
Thank You so much :)

**Comment by therajanmaurya** [comment]
Hi @hassanrehman01398 @ykhade, 

I am not able to run the app with above schema. 

can you guys please post your whole schema screenshots here? It would be big help.

![image](https://user-images.githubusercontent.com/5724482/86144831-cc9f8300-bb13-11ea-9def-e6e18c2d31a7.png)
![image](https://user-images.githubusercontent.com/5724482/86144920-eccf4200-bb13-11ea-8e90-47bb2524e58c.png)
![image](https://user-images.githubusercontent.com/5724482/86144937-f35db980-bb13-11ea-8094-d6aab70e358d.png)
